name: Lint

on:
  pull_request:

jobs:
  run-linting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: proof-html
        uses: anishathalye/proof-html@v2
        with:
          directory: ./website
          enforce_https: false
          check_html: false
          ignore_url: |
            https://www.instagram.com/funkmushanft/